# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(339, 326)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 341, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 8, 500, 16))
        self.label_5.setObjectName("label_5")
        self.hide = QtWidgets.QPushButton(self.widget)
        self.hide.setGeometry(QtCore.QRect(280, 0, 31, 31))
        self.hide.setMaximumSize(QtCore.QSize(40, 40))
        self.hide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.hide.setObjectName("hide")
        self.close = QtWidgets.QPushButton(self.widget)
        self.close.setGeometry(QtCore.QRect(310, 0, 31, 31))
        self.close.setMaximumSize(QtCore.QSize(40, 40))
        self.close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.close.setObjectName("close")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 325, 287))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox.setEditable(False)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.characters = QtWidgets.QComboBox(self.tab_6)
        self.characters.setObjectName("characters")
        self.horizontalLayout_2.addWidget(self.characters)
        self.addTask = QtWidgets.QPushButton(self.tab_6)
        self.addTask.setMaximumSize(QtCore.QSize(30, 16777215))
        self.addTask.setObjectName("addTask")
        self.horizontalLayout_2.addWidget(self.addTask)
        self.removeTask = QtWidgets.QPushButton(self.tab_6)
        self.removeTask.setMaximumSize(QtCore.QSize(30, 16777215))
        self.removeTask.setObjectName("removeTask")
        self.horizontalLayout_2.addWidget(self.removeTask)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 220))
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(9, 9, 20, 16))
        self.label.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label.setObjectName("label")
        self.keyMap = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyMap.setGeometry(QtCore.QRect(70, 9, 81, 18))
        self.keyMap.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keyMap.setObjectName("keyMap")
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(9, 33, 31, 16))
        self.label_2.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_2.setObjectName("label_2")
        self.keyAttack = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyAttack.setGeometry(QtCore.QRect(70, 33, 81, 18))
        self.keyAttack.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keyAttack.setObjectName("keyAttack")
        self.label_3 = QtWidgets.QLabel(self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(9, 57, 39, 16))
        self.label_3.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_3.setObjectName("label_3")
        self.keyInteract = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyInteract.setGeometry(QtCore.QRect(70, 57, 81, 18))
        self.keyInteract.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keyInteract.setObjectName("keyInteract")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(9, 81, 35, 16))
        self.label_4.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_4.setObjectName("label_4")
        self.keyJournal = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyJournal.setGeometry(QtCore.QRect(70, 81, 81, 18))
        self.keyJournal.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keyJournal.setObjectName("keyJournal")
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        self.label_7.setGeometry(QtCore.QRect(9, 105, 47, 16))
        self.label_7.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_7.setObjectName("label_7")
        self.keySwap = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keySwap.setGeometry(QtCore.QRect(70, 105, 81, 18))
        self.keySwap.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keySwap.setObjectName("keySwap")
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setGeometry(QtCore.QRect(9, 129, 47, 16))
        self.label_9.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_9.setObjectName("label_9")
        self.keyCardDuel = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyCardDuel.setGeometry(QtCore.QRect(70, 129, 81, 18))
        self.keyCardDuel.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keyCardDuel.setObjectName("keyCardDuel")
        self.label_10 = QtWidgets.QLabel(self.tab_7)
        self.label_10.setGeometry(QtCore.QRect(9, 153, 25, 16))
        self.label_10.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_10.setObjectName("label_10")
        self.keyJump = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyJump.setGeometry(QtCore.QRect(70, 153, 81, 18))
        self.keyJump.setMaximumSize(QtCore.QSize(81, 16777215))
        self.keyJump.setObjectName("keyJump")
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        self.label_13.setGeometry(QtCore.QRect(160, 10, 47, 16))
        self.label_13.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_13.setObjectName("label_13")
        self.keyUse = QtWidgets.QKeySequenceEdit(self.tab_7)
        self.keyUse.setGeometry(QtCore.QRect(210, 10, 81, 18))
        self.keyUse.setObjectName("keyUse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 40, 131, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.keyStart = QtWidgets.QKeySequenceEdit(self.groupBox_2)
        self.keyStart.setGeometry(QtCore.QRect(50, 20, 71, 18))
        self.keyStart.setObjectName("keyStart")
        self.keyStop = QtWidgets.QKeySequenceEdit(self.groupBox_2)
        self.keyStop.setGeometry(QtCore.QRect(50, 40, 71, 18))
        self.keyStop.setObjectName("keyStop")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 47, 16))
        self.label_14.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 47, 16))
        self.label_15.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_15.setObjectName("label_15")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabbbb = QtWidgets.QWidget()
        self.tabbbb.setObjectName("tabbbb")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tabbbb)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.tabbbb)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.deckStandard = QtWidgets.QComboBox(self.tabbbb)
        self.deckStandard.setObjectName("deckStandard")
        self.deckStandard.addItem("")
        self.deckStandard.addItem("")
        self.deckStandard.addItem("")
        self.deckStandard.addItem("")
        self.deckStandard.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deckStandard)
        self.label_11 = QtWidgets.QLabel(self.tabbbb)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.deck3StarWar = QtWidgets.QComboBox(self.tabbbb)
        self.deck3StarWar.setObjectName("deck3StarWar")
        self.deck3StarWar.addItem("")
        self.deck3StarWar.addItem("")
        self.deck3StarWar.addItem("")
        self.deck3StarWar.addItem("")
        self.deck3StarWar.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deck3StarWar)
        self.tabWidget_2.addTab(self.tabbbb, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.addTask_4 = QtWidgets.QPushButton(self.tab_2)
        self.addTask_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.addTask_4.setObjectName("addTask_4")
        self.horizontalLayout_6.addWidget(self.addTask_4)
        self.removeTask_4 = QtWidgets.QPushButton(self.tab_2)
        self.removeTask_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.removeTask_4.setObjectName("removeTask_4")
        self.horizontalLayout_6.addWidget(self.removeTask_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.tableView_3 = QtWidgets.QTableView(self.tab_2)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_6.addWidget(self.tableView_3)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.paragonItem = QtWidgets.QLineEdit(self.tab_8)
        self.paragonItem.setObjectName("paragonItem")
        self.horizontalLayout_3.addWidget(self.paragonItem)
        self.addParagonItem = QtWidgets.QPushButton(self.tab_8)
        self.addParagonItem.setMaximumSize(QtCore.QSize(30, 16777215))
        self.addParagonItem.setObjectName("addParagonItem")
        self.horizontalLayout_3.addWidget(self.addParagonItem)
        self.removeParagonItem = QtWidgets.QPushButton(self.tab_8)
        self.removeParagonItem.setMaximumSize(QtCore.QSize(30, 16777215))
        self.removeParagonItem.setObjectName("removeParagonItem")
        self.horizontalLayout_3.addWidget(self.removeParagonItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox.setStyleSheet("QGroupBox { margin-top: -10px; }")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.testParagon = QtWidgets.QPushButton(self.groupBox)
        self.testParagon.setGeometry(QtCore.QRect(10, 100, 81, 23))
        self.testParagon.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.testParagon.setObjectName("testParagon")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 81, 71))
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_12.setStyleSheet("QLabel { background-color : gray}")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setText("")
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 1)
        self.paragonTable = QtWidgets.QTableWidget(self.tab_8)
        self.paragonTable.setObjectName("paragonTable")
        self.paragonTable.setColumnCount(0)
        self.paragonTable.setRowCount(0)
        self.gridLayout_3.addWidget(self.paragonTable, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(0, 140))
        self.label_6.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_6.setStyleSheet("QLabel { background-color : gray}")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setText("")
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.screenshot = QtWidgets.QPushButton(self.tab_3)
        self.screenshot.setObjectName("screenshot")
        self.horizontalLayout_5.addWidget(self.screenshot)
        self.load = QtWidgets.QPushButton(self.tab_3)
        self.load.setEnabled(True)
        self.load.setObjectName("load")
        self.horizontalLayout_5.addWidget(self.load)
        self.save = QtWidgets.QPushButton(self.tab_3)
        self.save.setEnabled(False)
        self.save.setObjectName("save")
        self.horizontalLayout_5.addWidget(self.save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox.setToolTipDuration(5)
        self.doubleSpinBox.setFrame(True)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setReadOnly(False)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setKeyboardTracking(True)
        self.doubleSpinBox.setDecimals(2)
        self.doubleSpinBox.setMaximum(0.99)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.9)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox)
        self.testscreen = QtWidgets.QPushButton(self.tab_3)
        self.testscreen.setEnabled(False)
        self.testscreen.setObjectName("testscreen")
        self.horizontalLayout_4.addWidget(self.testscreen)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon)
        self.start.setIconSize(QtCore.QSize(15, 15))
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.stop = QtWidgets.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon1)
        self.stop.setIconSize(QtCore.QSize(15, 15))
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EasyAK"))
        self.label_5.setText(_translate("Dialog", "EasyAK 19321.3921b"))
        self.hide.setText(_translate("Dialog", "-"))
        self.close.setText(_translate("Dialog", "X"))
        self.comboBox.setCurrentText(_translate("Dialog", "Dungeon Leech"))
        self.comboBox.setItemText(0, _translate("Dialog", "Dungeon Leech"))
        self.comboBox.setItemText(1, _translate("Dialog", "Daily Field Quests"))
        self.comboBox.setItemText(2, _translate("Dialog", "Paragon Autoroll"))
        self.comboBox.setItemText(3, _translate("Dialog", "Fight Club & Ruins Defense"))
        self.comboBox.setItemText(4, _translate("Dialog", "Card Duels"))
        self.addTask.setText(_translate("Dialog", "+"))
        self.removeTask.setText(_translate("Dialog", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Queue Tasks"))
        self.label.setText(_translate("Dialog", "Map"))
        self.keyMap.setKeySequence(_translate("Dialog", "M"))
        self.label_2.setText(_translate("Dialog", "Attack"))
        self.keyAttack.setKeySequence(_translate("Dialog", "1"))
        self.label_3.setText(_translate("Dialog", "Interact"))
        self.keyInteract.setKeySequence(_translate("Dialog", "V"))
        self.label_4.setText(_translate("Dialog", "Journal"))
        self.keyJournal.setKeySequence(_translate("Dialog", "J"))
        self.label_7.setText(_translate("Dialog", "Swap"))
        self.label_9.setText(_translate("Dialog", "Card Duel"))
        self.label_10.setText(_translate("Dialog", "Jump"))
        self.keyJump.setKeySequence(_translate("Dialog", "Space"))
        self.label_13.setText(_translate("Dialog", "Use Item"))
        self.keyUse.setKeySequence(_translate("Dialog", "Z"))
        self.groupBox_2.setTitle(_translate("Dialog", "Macro Shortcuts"))
        self.label_14.setText(_translate("Dialog", "Start"))
        self.label_15.setText(_translate("Dialog", "Stop"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Dialog", "Key Bindings"))
        self.label_8.setText(_translate("Dialog", "Standard Battle"))
        self.deckStandard.setItemText(0, _translate("Dialog", "Deck 1"))
        self.deckStandard.setItemText(1, _translate("Dialog", "Deck 2"))
        self.deckStandard.setItemText(2, _translate("Dialog", "Deck 3"))
        self.deckStandard.setItemText(3, _translate("Dialog", "Deck 4"))
        self.deckStandard.setItemText(4, _translate("Dialog", "Deck 5"))
        self.label_11.setText(_translate("Dialog", "3-Star War"))
        self.deck3StarWar.setItemText(0, _translate("Dialog", "Deck 1"))
        self.deck3StarWar.setItemText(1, _translate("Dialog", "Deck 2"))
        self.deck3StarWar.setItemText(2, _translate("Dialog", "Deck 3"))
        self.deck3StarWar.setItemText(3, _translate("Dialog", "Deck 4"))
        self.deck3StarWar.setItemText(4, _translate("Dialog", "Deck 5"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabbbb), _translate("Dialog", "Card Duel"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Enter Character\'s Name"))
        self.addTask_4.setText(_translate("Dialog", "+"))
        self.removeTask_4.setText(_translate("Dialog", "-"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Dialog", "Characters"))
        self.paragonItem.setPlaceholderText(_translate("Dialog", "Enter Item Name"))
        self.addParagonItem.setText(_translate("Dialog", "+"))
        self.removeParagonItem.setText(_translate("Dialog", "-"))
        self.groupBox.setTitle(_translate("Dialog", "Preview"))
        self.testParagon.setText(_translate("Dialog", "Test Icon"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("Dialog", "Paragon Items"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Log"))
        self.screenshot.setText(_translate("Dialog", "Screenshot"))
        self.load.setText(_translate("Dialog", "Load"))
        self.save.setText(_translate("Dialog", "Save"))
        self.doubleSpinBox.setToolTip(_translate("Dialog", "Detection Accuracy"))
        self.testscreen.setText(_translate("Dialog", "Test Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Debug"))
        self.start.setText(_translate("Dialog", "  Start (Shift+F1)"))
        self.stop.setText(_translate("Dialog", "  Stop (Shift+F2)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
